version: "3.9"

services:
  web:
    build: .docker
    volumes:
      - .:/app/
    ports:
      - 3000:3000
    command: ["yarn", "--cwd=/app", "start"]

  mariadb:
    image: mariadb:latest
    volumes:
      - ../.data_mysql:/var/lib/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: anetdb
      MYSQL_USER: userdb
      MYSQL_PASSWORD: passdb
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: userdb
      PMA_PASSWORD: passdb
    links:
      - mariadb
    depends_on:
      - mariadb

  redis:
    image: redis
    ports:
      - "6379:6379"
